[package]
name = "game-lang"
version = "0.1.0"
authors = ["Heman Gandhi <hemangandhi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-tungstenite = "0.12.0"